---

- name: install required packages
  apt:
    pkg: 
      - adduser 
      - libfontconfig1 
    state: present
    update_cache: yes

- name: install grafana
  apt:
    deb: https://dl.grafana.com/oss/release/grafana_7.3.6_amd64.deb
  notify:
    - reload systemctl

- name: start grafana service
  service: name=grafana-server.service state=restarted enabled=yes

- name: check if grafana is accessible.
  uri:
    url: http://{{ inventory_hostname }}:3000
    method: GET
    status_code: 200