- name: web
  hosts: web
  serial: 1

  tasks:
    - name: Get old deployed hash
      stat:
        path: /opt/glimesh.tv-old
        follow: yes
        get_checksum: no
      register: old_deploy

    - name: Change the symlink
      file:
        src: "{{ old_deploy.stat.lnk_target }}"
        dest: /opt/glimesh.tv
        state: link
        owner: nobody
        force: yes

    - name: restart glimesh
      systemd:
        name: glimesh
        daemon_reload: yes
        state: restarted

    - name: wait for service to be online
      wait_for:
        port: 8080
        delay: 5

    - name: pause to make sure the other node can take over
      pause:
        seconds: 15
